version: "3.1"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 5173:5173

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      POSTGRES_DB: backend_dev
      PGDATA: /var/lib/postgresql/data/pgdataprod
    volumes:
      - "pgdataprod:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    # healthcheck:
    # test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
    # interval: 10s
    # timeout: 10s
    # retries: 10

  adminer:
    image: adminer
    ports:
      - 8000:8080

volumes:
  pgdataprod:
